baseURL = "https://elacanan.github.io/"
languageCode = "en-us"
title = "Hey, I'm Ela."
theme = "hello-friend-ng"

[params]
  description = "Welcome to my personal website!"
  author = "Ela Albiston"
  showReadingTime = true
  enableThemeToggle = true

[params.logo]
  logoMark = ">"
  logoText = "$ cd /home/ela"
  logoHomeLink = "/"

  [[params.social]]
    name = "email"
    url  = "mailto:elajalbiston@gmail.com"
    rel = "noopener noreferrer"
    target = "_blank"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/ela-albiston"
    rel = "noopener noreferrer"
    target = "_blank"
  
  [[params.social]]
    name = "github"
    url  = "https://github.com/elacanan"
    rel = "noopener noreferrer"
    target = "_blank"

[menu]
  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 2

  [[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 1
